doc: add document for outputs
serverless-components/tencent-koa pull request #44
Opened 2021-01-13 02:59 UTC by wwwzbwcom

2021-01-13 07:49 UTC, yugasun requested changes

2021-01-13 07:49 UTC, yugasun commented on README.md
> +- [点击此处查看配置文档](./docs/configure.md)
这里需要保持 github 全链接，方便爬虫获取

2021-01-15 02:36 UTC, wwwzbwcom commented on README.md
> +- [点击此处查看配置文档](./docs/configure.md)
resolved~ @yugasun

2021-01-18 02:32 UTC, yugasun requested changes

2021-01-18 02:32 UTC, yugasun commented on README.md
> +- [点击此处查看输出文档](https://github.com/serverless-components/tencent-koa/tree/master/docs/output.md)
输出文档链接最好放到 `部署步骤` 后面进行说明

2021-01-18 07:15 UTC, wwwzbwcom commented on README.md
> +- [点击此处查看输出文档](https://github.com/serverless-components/tencent-koa/tree/master/docs/output.md)
resolved~

2021-01-18 11:29 UTC, yugasun approved these changes
Well done.

2021-01-18 11:29 UTC, merged

2021-01-26 12:49 UTC, slsplus commented
:tada: This PR is included in version 0.4.0 :tada:

The release is available on [GitHub release](https://github.com/serverless-components/tencent-koa/releases/tag/v0.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: